AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation para crear una user pool en cognito con flujos OAuth'
Parameters:
  AmplifyAppURL:  
    Type: String
    Description: "URL base for the Amplify app (without https:// and trailing slash)"

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AliasAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireUppercase: true
          RequireSymbols: true
      Schema:
        - AttributeDataType: String
          Mutable: true
          Name: email
          Required: true
          StringAttributeConstraints:
            MinLength: "1"

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      SupportedIdentityProviders:
        - COGNITO
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED

Outputs:
  CognitoUserPoolID:
    Description: 'The UserPool ID'
    Value: !Ref UserPool
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolId"
  CognitoAppClientID:
    Description: 'The app client ID'
    Value: !GetAtt UserPoolClient.ClientId
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolWebClientId"
