version: "3.9"

services:
  # client:
  #   container_name: client
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   tty: true
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - "./frontend:/app"
  #     - /app/node_modules
  #   networks:
  #     - frontend
  #   environment:
  #     WATCHPACK_POLLING: true

  uploader:
    container_name: uploader
    build:
      context: ./uploader
      dockerfile: Dockerfile
    command: >
      gunicorn 
      --bind 0.0.0.0:8094 
      --timeout 3000
      app:app
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: 2G
    depends_on:
      - mongodb
    environment:
      MONGO_URI: >-
        mongodb://admin:password@mongodb:27017/webapp?authMechanism=SCRAM-SHA-256&authSource=admin&ssl=false
    ports:
      - "8094:8094"
    volumes:
      - "./uploader:/app"
    networks:
      - backend
      - frontend

  python-selenium:
    container_name: python-selenium
    privileged: true
    build:
      context: ./python_scrappers
      dockerfile: Dockerfile
    command: >
      gunicorn 
      --bind 0.0.0.0:8093 
      --timeout 3000
      app:app
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: 2G
    depends_on:
      - mongodb
    environment:
      MONGO_URI: >-
        mongodb://admin:password@mongodb:27017/webapp?authMechanism=SCRAM-SHA-256&authSource=admin&ssl=false
    ports:
      - "8093:8093"
    volumes:
      - "./python_scrappers:/app"
    networks:
      - backend
      - frontend

  mongodb:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: webapp
      MONGODB_DATA_DIR: /data/db
    volumes:
      - "mongodbdata:/data/db"
    networks:
      - backend
    ports:
      - "27017:27017"

  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: "gunicorn --bind 0.0.0.0:8082 app:app"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
    ports:
      - "8082:8082"
    environment:
      MONGO_URI: >-
        mongodb://admin:password@mongodb:27017/webapp?authMechanism=SCRAM-SHA-256&authSource=admin&ssl=false
    volumes:
      - "./src:/src"
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend

  mongo-express:
    image: mongo-express
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 0.5G
    ports:
      - 8090:8081
    networks:
      - backend
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: joselikiuser
      ME_CONFIG_BASICAUTH_PASSWORD: joselikipass
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_URL: >-
        mongodb://admin:password@mongo

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
