AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.12
  Sample SAM Template for python_scrappers

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 29
    Architectures: x86_64
    MemorySize: 10240 # 8192 #4096
    Environment:
      Variables:
        ENVIRONMENT: dev

    Tags:
      project: descuentapp
      environment: develop

Resources:
  AlcampoScrappingLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole # Política de IAM básica para ejecución de Lambda
        - AmazonDynamoDBFullAccess # Ejemplo de política adicional, ajustar según necesidad
      ReservedConcurrentExecutions: 1
      Events:
        FlaskAppAPI:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
    Metadata:
      # Dockerfile: Dockerfile.alcampo.lambda
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  AlcampoScrappingLambdaFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt AlcampoScrappingLambdaFunction.Arn
  AlcampoScrappingLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt AlcampoScrappingLambdaFunctionRole.Arn
