AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.12
  Sample SAM Template for python_scrappers

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    Architectures: x86_64
    MemorySize:  512 #10240 # 8192 #4096
    EphemeralStorage:
        Size: 512
    Environment:
      Variables:
        ENVIRONMENT: dev

    Tags:
      project: descuentapp
      environment: develop

Resources:
  ProductPricesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ScrappedProductsTable
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 15
        WriteCapacityUnits: 15
      AttributeDefinitions:
      - AttributeName: origin
        AttributeType: S
      - AttributeName: timestamp
        AttributeType: N
      - AttributeName: pname
        AttributeType: S
      KeySchema:
      - AttributeName: origin
        KeyType: HASH
      - AttributeName: timestamp
        KeyType: RANGE
      GlobalSecondaryIndexes:
      - IndexName: NameIndex
        KeySchema:
        - AttributeName: pname
          KeyType: HASH
        Projection:
          ProjectionType: INCLUDE
          NonKeyAttributes:
          - price_per_unit
          - total_price
          - image_url
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

  MySQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "MiColaSQS"
      VisibilityTimeout: 900

  LambdaDispatcher:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile.event_processor
      DockerContext: ./
      DockerTag: v1
    Properties:
      PackageType: Image
      Timeout: 900
      MemorySize:  4096
      EphemeralStorage:
        Size: 2048
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
        - AmazonSQSFullAccess
      Architectures:
        - x86_64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MySQSQueue.Arn
            BatchSize: 1

  AlcampoScrappingLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Policies:

        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
        - AmazonSQSFullAccess

      Events:
        FlaskAppAPI:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
    Metadata:
      # Dockerfile: Dockerfile.alcampo.lambda
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: v1


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  AlcampoScrappingLambdaFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt AlcampoScrappingLambdaFunction.Arn
  AlcampoScrappingLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt AlcampoScrappingLambdaFunctionRole.Arn
