AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation para crear un bucket de S3'

Resources:
  AmplifyFrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: frontend-amplify-jmc

Outputs:
  BucketName:
    Value: !Ref AmplifyFrontendBucket
    Description: Nombre del Bucket de S3