name: Deploy frontend in github actions with pnpm

on:
  push:
    branches: [feature/frontend_gh_deploy]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'    
      - name: set up node js
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'p'
      - name: install pnpm
        run: npm install -g pnpm
      - name: install dependencies
        run: pnpm install
      - name: build docker
        run: |
          docker compose build . -t frontend
      
