name: Deploy frontend in github actions with pnpm

on:
  push:
    branches: [feature/frontend_gh_deploy]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

        with:
          python-version: '3.11'    

      - name: set up node js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: install dependencies
        run: pnpm install
        working-directory: frontend
        
      - name: Build with pnpm
        run: pnpm run build
        working-directory: frontend
        
      
      - name: ls 
        run: ls -la
        working-directory: frontend/build/static

      - name: ls 
        run: ls -la
        working-directory: frontend/build/static/js
      
      - name: ls 
        run: ls -la
        working-directory: frontend/build/static/css
