name: Deploy frontend in github actions with pnpm

on:
  push:
    workflow_run:
      workflows:
        - 🧪⚛️[Tests][Unit] Frontend
      branches:
        [feature/frontend_gh_deploy]
      types:
        - completed
env:
      S3_BUCKET: frontend-amplify-descuentapp
      ARTIFAC_NAME: build.zip
      AMPLIFY_APP_NAME: descuentapp

permissions:
  id-token: write
  contents: read


jobs:
  check-tests:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

  build-and-deploy:
    needs: check-tests
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
      
      - name: set up node js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: install dependencies
        run: pnpm install
        working-directory: frontend
        
      - name: Build with pnpm
        run: pnpm run build
        working-directory: frontend
      
      - name: Zip build directory
        run: zip -r build.zip .
        working-directory: frontend/build

      - name: "Setup AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Upload to S3
        run: aws s3 cp build.zip s3://$S3_BUCKET/build.zip
        working-directory: frontend/build

      - name: Start Deployment to Amplify
        shell: bash
        run: |
              AMPLIFY_APP_ID=$(aws amplify list-apps | jq -r --arg AMPLIFY_APP_NAME "$AMPLIFY_APP_NAME" '.apps[] | select((.name==$AMPLIFY_APP_NAME)) | .appId')
              AMPLIFY_APP_BRANCH="feature/frontend_gh_deploy"
              aws amplify start-deployment \
              --app-id $AMPLIFY_APP_ID \
              --branch-name $AMPLIFY_APP_BRANCH \
              --source-url s3://$S3_BUCKET/$ARTIFAC_NAME
      