name: Deploy frontend in github actions with pnpm

on:
  push:
    branches:
      - feature/frontend_gh_deploy

  workflow_run:
    workflows:
      - '🧪⚛️[Tests][Unit] Frontend'
    types:
      - completed
env:
      S3_BUCKET: frontend-amplify-descuentapp
      ARTIFAC_NAME: build.zip
      AMPLIFY_APP_NAME: descuentapp

permissions:
  id-token: write
  contents: read


jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
        node-version:
          - "16.20.2"
          - "18.20.2"
          - "20.12.2"
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      name: Checkout code
      with:
          fetch-depth: 0

    - uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Install dependencies and run tests
      working-directory: frontend
      run: pnpm install-test

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: set up node js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: install dependencies
        run: pnpm install
        working-directory: frontend
        
      - name: Build with pnpm
        run: pnpm run build
        working-directory: frontend
      
      - name: Zip build directory
        run: zip -r build.zip .
        working-directory: frontend/build

      - name: "Setup AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Upload to S3
        run: aws s3 cp build.zip s3://$S3_BUCKET/build.zip
        working-directory: frontend/build

      - name: Start Deployment to Amplify
        shell: bash
        run: |
              AMPLIFY_APP_ID=$(aws amplify list-apps | jq -r --arg AMPLIFY_APP_NAME "$AMPLIFY_APP_NAME" '.apps[] | select((.name==$AMPLIFY_APP_NAME)) | .appId')
              AMPLIFY_APP_BRANCH="feature/frontend_gh_deploy"
              aws amplify start-deployment \
              --app-id $AMPLIFY_APP_ID \
              --branch-name $AMPLIFY_APP_BRANCH \
              --source-url s3://$S3_BUCKET/$ARTIFAC_NAME
      