name: 🧪📺[Tests][E2E] Frontend

on: 
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:
  push:
    # paths:
    #   - 'frontend/**'
    #   - '.github/test_integration_frontend.yml'

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Install Cypress
        run: npm install cypress --save-dev

      - name: Run Cypress tests
        run: npm run e2e

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
