name: 🧪📺[Tests][E2E] Frontend

on: 
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:
  push:
    # paths:
    #   - 'frontend/**'
    #   - '.github/test_integration_frontend.yml'

jobs:
  e2e-cypress-tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
        node-version:
          - "18.20.2"
          - "20.12.2"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        working-directory: frontend
        run: pnpm install --no-frozen-lockfile

      - name: Install Cypress
        working-directory: frontend
        run: pnpm install cypress --save-dev

      - name: Run Cypress tests
        working-directory: frontend
        run: pnpm run e2e

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-${{ matrix.node-version }}-${{ matrix.os }}
          path: ${{ github.workspace }}/frontend/cypress/videos
          retention-days: 90

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-${{ matrix.node-version }}-${{ matrix.os }}
          path: ${{ github.workspace }}/frontend/cypress/screenshots
          retention-days: 90
